package connection.packet;

public enum PacketType {
    REGISTER_PACKET,
    LOGIN_PACKET,
    TILES_PACKET,
    POPUP_PACKET,
    USER_PACKET,
    FRIEND_REQUEST_PACKET,
    CHAT_PACKET,
    NEW_MESSAGE_PACKET,
    EDIT_MESSAGE_PACKET,
    DELETE_MESSAGE_PACKET
}